# Generated by Django 4.2.1 on 2023-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('stato', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
