# Generated by Django 4.2.1 on 2023-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_categoria_task_utente_alter_task_stato_commento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stato',
            field=models.TextField(),
        ),
    ]
