# Generated by Django 4.2.1 on 2023-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Personale', 'Personale'), ('Lavoro', 'Lavoro')], max_length=100),
        ),
    ]
