# Generated by Django 4.2.1 on 2023-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_allegato_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stato',
            field=models.CharField(choices=[('da_fare', 'Da fare'), ('in_corso', 'In corso'), ('fatto', 'Fatto')], default='da_fare', max_length=20),
        ),
    ]
