# Generated by Django 4.2.1 on 2023-06-03 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0008_alter_task_stato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='utente',
        ),
        migrations.AddField(
            model_name='task',
            name='utenti',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
