# Generated by Django 4.2.1 on 2023-06-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_remove_task_utente_task_utenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='utenti',
        ),
        migrations.AddField(
            model_name='task',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
