# Generated by Django 4.2.1 on 2023-06-03 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_remove_task_utente_task_utenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='utenti',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
