# Generated by Django 4.2.1 on 2023-06-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='utenti',
        ),
    ]
