# Generated by Django 4.2.1 on 2023-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_task_utenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gestione',
            field=models.CharField(choices=[('Privato', 'Privato'), ('Pubblico', 'Pubblico')], default='Privato', max_length=20),
        ),
    ]
