# Generated by Django 4.2.1 on 2023-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_remove_task_gestione'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gestione',
            field=models.CharField(choices=[('privato', 'Privato'), ('pubblico', 'Pubblico')], default='privato', max_length=20),
        ),
    ]
