# Generated by Django 4.2.1 on 2023-06-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_taskteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commento',
            name='task',
        ),
        migrations.RemoveField(
            model_name='commento',
            name='utente',
        ),
        migrations.DeleteModel(
            name='Allegato',
        ),
        migrations.DeleteModel(
            name='Commento',
        ),
    ]
