# Generated by Django 4.2.1 on 2023-06-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0021_remove_commento_task_remove_commento_utente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('da_fare', 'Da fare'), ('in_corso', 'In corso'), ('fatto', 'Fatto')], default='da_fare', max_length=20)),
                ('gestione', models.CharField(choices=[('privato', 'Privato'), ('pubblico', 'Pubblico')], default='privato', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.categoria')),
                ('utenti', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
