# Generated by Django 4.2.1 on 2023-06-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_gruppo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTeam',
        ),
    ]
